<?php

namespace AppBundle\Repository;

/**
 * AllFormsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllFormsRepository extends \Doctrine\ORM\EntityRepository
{
}
