app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /admin

api_login_check:
    path: /api/login_check