register:
    path: /register
    methods: [POST]
    defaults: { _controller: AppBundle:Registration:register}

login:
    path: /login
    methods: [POST]
    defaults: { _controller: AppBundle:Login:login}

auth:
    path: /auth
    methods: [POST]
    defaults: { _controller: AppBundle:Authentication:Authenticate}

forms:
    path: /forms
    methods: [GET]
    defaults: { _controller: AppBundle:Form:form}