homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

register:
    path: /register
    methods: [POST]
    defaults: { _controller: AppBundle:Registration:register}

register:
    path: /login
    methods: [POST]
    defaults: { _controller: AppBundle:Login:login}