register:
    path: /register
    methods: [POST]
    defaults: { _controller: AppBundle:Registration:register}

login:
    path: /login
    methods: [POST]
    defaults: { _controller: AppBundle:Login:login}

auth:
    path: /auth
    methods: [POST]
    defaults: { _controller: AppBundle:Authentication:Authenticate}

user_promote:
    path: /user/promote
    methods: [POST]
    defaults: { _controller: AppBundle:ApiUser:promote}

user_demote:
    path: /user/demote
    methods: [POST]
    defaults: { _controller: AppBundle:ApiUser:demote}

forms:
    path: /forms
    methods: [GET]
    defaults: { _controller: AppBundle:Form:form}